# Generated by Django 5.0.6 on 2024-05-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('rarity', models.CharField()),
                ('image', models.CharField()),
                ('prices', models.JSONField(default=list)),
                ('highest_market_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('rarity', models.CharField()),
                ('image', models.CharField()),
                ('prices', models.JSONField(default=list)),
                ('highest_market_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField()),
                ('name', models.CharField()),
                ('rarity', models.CharField()),
                ('image', models.CharField()),
                ('prices', models.JSONField(default=list)),
                ('highest_market_price', models.FloatField()),
                ('types', models.ManyToManyField(to='pokedex.type')),
            ],
        ),
    ]
