# Generated by Django 5.0.6 on 2024-05-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='energy',
            name='card_id',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='trainer',
            name='card_id',
            field=models.CharField(default=None),
        ),
    ]
