# Generated by Django 5.0.6 on 2024-05-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_options_energy_card_id_trainer_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energy',
            name='rarity',
        ),
    ]
