# Generated by Django 5.0.6 on 2024-05-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_remove_energy_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
