# Generated by Django 5.0.6 on 2024-06-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_pokemonnames'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='energy',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['name']},
        ),
    ]
