# Generated by Django 5.0.6 on 2024-06-11 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_energynames_trainernames_alter_energy_options_and_more'),
        ('pokedex', '0005_trainernames'),
    ]

    operations = [
    ]
